services:
  ubuntu-proxy:
    build:
      dockerfile: "ubuntu/Dockerfile"
      context: .
      platforms:
        - linux/amd64
    volumes:
      - "./certs/proxy/:/etc/ssl/proxy"
      - "./passwd:/etc/nginx/passwd"
      - "./keys:/etc/nginx/keys"
    environment:
      TZ: "UTC"

      # config generator settings
      HFP_PROXIES: tls,mtls,basic,digest,bearer,ws
      HFP_DEBUG_CONF: "true"

      # global nginx/openresty settings
      HFP_USER: "root"

      # standard server-side-tls server
      HFP_tls_PORT: 3128
      HFP_tls_SSL: "true"
      HFP_tls_SSL_CERTIFICATE: /etc/ssl/proxy/proxy.crt
      HFP_tls_SSL_PRIVATE_KEY: /etc/ssl/proxy/proxy.key

      # mtls server
      HFP_mtls_PORT: 3129
      HFP_mtls_SSL: "true"
      HFP_mtls_SSL_CERTIFICATE: /etc/ssl/proxy/proxy.crt
      HFP_mtls_SSL_PRIVATE_KEY: /etc/ssl/proxy/proxy.key
      HFP_mtls_SSL_CLIENT_CERTIFICATE: /etc/ssl/proxy/ca.crt

      # server-side tls + Basic Auth
      HFP_basic_PORT: 3130
      HFP_basic_SSL: "true"
      HFP_basic_SSL_CERTIFICATE: /etc/ssl/proxy/proxy.crt
      HFP_basic_SSL_PRIVATE_KEY: /etc/ssl/proxy/proxy.key
      HFP_basic_AUTH: basic
      HFP_basic_AUTH_BASIC_PASSWD: /etc/nginx/passwd/basic.passwd

      # server-side tls + Bearer Auth
      HFP_bearer_PORT: 3131
      HFP_bearer_SSL: "true"
      HFP_bearer_SSL_CERTIFICATE: /etc/ssl/proxy/proxy.crt
      HFP_bearer_SSL_PRIVATE_KEY: /etc/ssl/proxy/proxy.key
      HFP_bearer_AUTH: bearer
      HFP_bearer_AUTH_BEARER_JWKS: /etc/nginx/keys/keys.jwks

      # plain/text + digest auth
      HFP_digest_PORT: 3132
      HFP_digest_AUTH: digest
      HFP_digest_AUTH_DIGEST_PASSWD: /etc/nginx/passwd/digest.passwd
      
    ports:
      - "8080:80"
      - "3128:3128"
      - "3129:3129"
      - "3130:3130"
      - "3131:3138"
      - "8080:80"


#  redhat-proxy:
#    build:
#      dockerfile: "redhat/Dockerfile"
#      context: .
#    volumes:
#      - "./certs/proxy/:/etc/ssl/proxy"
#      - "./passwd:/etc/nginx/passwd"
#      - "./keys:/etc/nginx/keys"
#    environment:
#      TZ: "UTC"
# 
#      # config generator settings
#      HFP_PROXIES: tls,mtls,basic,digest,bearer
#      HFP_DEBUG_CONF: "true"
# 
#      # global nginx/openresty settings
#      HFP_USER: "root"
# 
#      # standard server-side-tls server
#      HFP_tls_PORT: 3128
#      HFP_tls_SSL: "true"
#      HFP_tls_SSL_CERTIFICATE: /etc/ssl/proxy/proxy.crt
#      HFP_tls_SSL_PRIVATE_KEY: /etc/ssl/proxy/proxy.key
# 
#      # mtls server
#      HFP_mtls_PORT: 3129
#      HFP_mtls_SSL: "true"
#      HFP_mtls_SSL_CERTIFICATE: /etc/ssl/proxy/proxy.crt
#      HFP_mtls_SSL_PRIVATE_KEY: /etc/ssl/proxy/proxy.key
#      HFP_mtls_SSL_CLIENT_CERTIFICATE: /etc/ssl/proxy/ca.crt
# 
#      # server-side tls + Basic Auth
#      HFP_basic_PORT: 3130
#      HFP_basic_SSL: "true"
#      HFP_basic_SSL_CERTIFICATE: /etc/ssl/proxy/proxy.crt
#      HFP_basic_SSL_PRIVATE_KEY: /etc/ssl/proxy/proxy.key
#      HFP_basic_AUTH: basic
#      HFP_basic_AUTH_BASIC_PASSWD: /etc/nginx/passwd/basic.passwd
# 
#      # server-side tls + Bearer Auth
#      HFP_bearer_PORT: 3131
#      HFP_bearer_SSL: "true"
#      HFP_bearer_SSL_CERTIFICATE: /etc/ssl/proxy/proxy.crt
#      HFP_bearer_SSL_PRIVATE_KEY: /etc/ssl/proxy/proxy.key
#      HFP_bearer_AUTH: bearer
#      HFP_bearer_AUTH_BEARER_JWKS: /etc/nginx/keys/keys.jwks
# 
#      # plain/text + digest auth
#      HFP_digest_PORT: 3132
#      HFP_digest_AUTH: digest
#      HFP_digest_AUTH_DIGEST_PASSWD: /etc/nginx/passwd/digest.passwd
# 
#    ports:
#      - "8080:80"
#      - "3128:3128"
#      - "3129:3129"
#      - "3130:3130"
#      - "3131:3138"
#      - "8080:80"
