/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.InputStream;
import java.net.URI;
import java.security.KeyManagementException;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.UnrecoverableKeyException;

import javax.net.ssl.SSLContext;

import org.apache.hc.client5.http.auth.CredentialsProvider;
import org.apache.hc.client5.http.classic.methods.HttpGet;
import org.apache.hc.client5.http.impl.DefaultAuthenticationStrategy;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.CloseableHttpResponse;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager;
import org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManagerBuilder;
import org.apache.hc.client5.http.ssl.DefaultClientTlsStrategy;
import org.apache.hc.client5.http.ssl.TlsSocketStrategy;
import org.apache.hc.core5.http.HttpEntity;
import org.apache.hc.core5.http.HttpHost;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.apache.hc.core5.ssl.SSLContexts;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
            throws KeyManagementException, UnrecoverableKeyException, KeyStoreException, Exception {
        App a = new App();
        String res = a.get("https://stallman.org");
         res = a.get("https://stallman.org");
         res = a.get("https://stallman.org");
         res = a.get("https://stallman.org");
        //System.out.println(res);
    }

    public String get(String url)
            throws KeyManagementException, UnrecoverableKeyException, KeyStoreException, Exception {

        SSLContext sslContext = SSLContexts.custom()
                .loadKeyMaterial(readClientCertStore(), "123".toCharArray())
                .loadTrustMaterial(readRootCertStore(), null)
                .build();

        final TlsSocketStrategy tlsStrategy = new DefaultClientTlsStrategy(sslContext);

        final PoolingHttpClientConnectionManager connectionManager = PoolingHttpClientConnectionManagerBuilder.create()
                .setTlsSocketStrategy(tlsStrategy).build();

        CredentialsProvider cp = new DynamicCredentials();
        CloseableHttpClient client = HttpClients.custom()
                .setProxy(HttpHost.create(URI.create("https://harness-fproxy:3128")))
                .setProxyAuthenticationStrategy(new DefaultAuthenticationStrategy())
                .setDefaultCredentialsProvider(cp)
                .setConnectionManager(connectionManager)
                .build();

        System.out.println("por hacer request");
        String resultContent = null;
        try (CloseableHttpResponse response = client.execute(new HttpGet(url))) {
            // Get status code
            System.out.println(response.getVersion()); // HTTP/1.1
            System.out.println(response.getCode()); // 200
            System.out.println(response.getReasonPhrase()); // OK
            HttpEntity entity = response.getEntity();
            // Get response information
            resultContent = EntityUtils.toString(entity);
        }
        return resultContent;
    }

    KeyStore readClientCertStore() throws Exception {
        try (InputStream keyStoreStream = App.class.getResourceAsStream("/client.p12")) {
            System.out.println(keyStoreStream.available());
            KeyStore keyStore = KeyStore.getInstance("PKCS12");
            keyStore.load(keyStoreStream, "123".toCharArray());
            return keyStore;
        }
    }

    KeyStore readRootCertStore() throws Exception {
        try (InputStream keyStoreStream = this.getClass().getResourceAsStream("/cacerts")) {
            KeyStore keyStore = KeyStore.getInstance("JKS");
            keyStore.load(keyStoreStream, "changeit".toCharArray());
            return keyStore;
        }
    }

}
