name: docker

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.run_number || github.event.pull_request.number }}
  cancel-in-progress: true

env:
  REGISTRY_IMAGE: ${{ vars.ECR_TESTING_URL }}/${{ github.event.repository.name }}

jobs:
  bpsdh:
    name: "Build platform-specific image for dockerhub"
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm-large' }}
    strategy:
      matrix:
        os:
          - redhat
          - ubuntu
        platform:
          - linux/amd64
          - linux/arm64
    defaults:
      run:
        shell: bash
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}-${{ matrix.os }}
          tags: type=sha

      # TODO(mredolatti): remove once all repos are public
      - name: Setup .netrc with permissions for private repos (Go dependencies)
        uses: danielr1996/envsubst-action@1.1.0
        env:
          TOKEN: ${{ secrets.DEVOPS_READONLY_GITHUB_TOKEN }}
        with:
          input: .netrc.tpl
          output: .netrc

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_RW_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' }}
          context: .
          file: ${{ matrix.os }}/Dockerfile
          tags: ${{ env.REGISTRY_IMAGE }}-${{ matrix.os }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/${{ matrix.os }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/${{ matrix.os }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.os }}-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/${{ matrix.os }}/digests/*
          if-no-files-found: error
          retention-days: 1

  mergedh:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - redhat
          - ubuntu
    needs:
      - bpsdh
    defaults:
      run:
        shell: bash
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/${{ matrix.os }}/digests
          pattern: digests-${{ matrix.os }}-*
          merge-multiple: true

      - name: Get version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      # TODO(mredolatti) Restore this jog with `latest` tags as well once job is working properly
      #- name: Prepare tags for docker images
      #  run: |
      #    export TAGS="splitsoftware/fme-proxy:${{ matrix.os }}-latest,splitsoftware/fme-proxy:${{ matrix.os }}-${VERSION}"
      #    [ "${{ matrix.os }}" == "ubuntu" ] && export TAGS="${TAGS},splitsoftware/fme-proxy:latest,splitsoftware/fme-proxy:${VERSION}"
      #    echo "TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Prepare tags for docker images
        run: |
          export TAGS="splitsoftware/fme-proxy:${{ matrix.os }}-${VERSION}"
          [ "${{ matrix.os }}" == "ubuntu" ] && export TAGS="${TAGS},splitsoftware/fme-proxy:${VERSION}"
          echo "TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/${{ matrix.os }}/digests
        run: |
          docker buildx imagetools create (while read tag; do printf -- "-t ${tag} "; done <<<"${TAGS//,/$'\n'}") \
            $(printf '${{ env.REGISTRY_IMAGE }}-${{ matrix.os }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}-${{ matrix.os }}:${{ steps.meta.outputs.version }}
