name: tests

on:
  push:
    branches-ignore:
      - main
  pull_request:
      - main

permissions:
  contents: read
  id-token: write

jobs:

  testgc:
    name: "test bash scripts"
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run genconf tests
        run: make test-scripts
