name: tests

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  id-token: write

jobs:

  testgc:
    name: 'test bash scripts'
    runs-on: 'ubuntu-24.04'
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run genconf tests
        run: make test-scripts
